#!/bin/bash

ME=$$
MEDIA=
DEST_DIR=
DEVICE="$DEVNAME"
TITLE_NAME="$ID_FS_LABEL" # Media title; usually the film name if a DVD/Bluray

# Configurable variables/parameters etc.
[ -f /etc/disc-trigger.conf ] && . /etc/disc-trigger.conf

check_fs() {
	local -r v=`grep -c " ${1} " /proc/mounts`
	[ $v = "1" ] && return 0 || return 1
}

generic_mount() {
	local -r u=`id -u ${USR}`
	local -r g=`id -g ${GRP}`

	[ ${NO_MOUNT} -eq 1 ] && return 0

	check_fs "/media/${MEDIA}" && return 1
	mount -o ro,nosuid,nodev,user,umask=0077,uid=${u},gid=${g} \
		${DEVICE} /media/${MEDIA}

	return $?
}

generic_umount() {
	[ ${NO_EJECT} -eq 1 ] && return 0

	check_fs "/media/${MEDIA}" && umount "/media/${MEDIA}"
	eject "${DEVICE}"

	return $?
}

run_encoder() {
	local -i audio_stream=`audio-info "$1" | audio-prefs ${AUDIO_PREFS_OPTS[@]}`
	nice -n ${ENCODER_PRIORITY} HandBrakeCLI "${HANDBRAKE_OPTS[@]}" \
		-a $(($audio_stream + 1)) \
		-i "$1" -o "$2"
}

identify_titles() {
	# If no titles have been set, locate the single main feature on disc
	if [ ${#TITLES[@]} -eq 0 ]
	then
		makemkvcon -r info dev:${DEVICE} 1> "/tmp/${MEDIA}.nfo" && \
		TITLES[0]=`blutit ${BLUTIT_OPTS[@]} "/tmp/${MEDIA}.nfo"`
	fi
}

extract_titles() {
	cd "$1" || return 1

	for t in ${TITLES[@]}
	do
		nice -n ${EXTRACT_PRIORITY} makemkvcon mkv dev:${DEVICE} "${t}" "$1"
		[ $? -eq 0 ] && mv "`ls -t1 *.mkv | head -n1`" "${TITLE_NAME}_t${t}.mkv"
	done

	cd "$OLDPWD" || return 1
}

rip_audio() {
	local p="/mnt/${DEST_DIR}"

	check_fs "$p" || return 1

	abcde -w 'Ripped with abcde' -N -d "${DEVICE}" \
		 && chown -R ${USR}:${GRP} "${p}"
}

rip_video() {
	local p="/mnt/${DEST_DIR}"
	local q="/mnt/${DEST_DIR}/queue"

	check_fs "$p" || return 1
	mkdir -p "$q" || return 1
	[ $QUEUE_RUN_ONLY -eq 1 ] || identify_titles || return 1
	[ $QUEUE_RUN_ONLY -eq 1 ] || extract_titles "$q" || return 1

	i=0
	for x in `ls -tr1 "$q"`
	do
		name="`echo $x | sed -r 's/_t[0-9]+.mkv$//' | tr A-Z a-z`"
		d="`echo ${p}/${CATEGORY}/${name:0:1}/${name}`"
		f="${TITLE_PREFIX}${name}${TITLE_SUFFIX}"

		if [ $i -gt 0 ]
		then
			e="-${i}.mkv"
		else
			e=".mkv"
		fi

		mkdir -p "${d}" && run_encoder "${q}/${x}" "${d}/${f}${e}" || continue
		[ -s "${d}/${f}${e}" ] || continue # Double (trivial) check!
		echo "${d}/${f}${e}" >> "${p}/${MEDIA}-rips.txt"
		rm "${q}/${x}"
		let i="i + 1"
	done

	chown -R ${USR}:${GRP} "${p}/${CATEGORY}"
}

sleep 2

if [ "$ID_CDROM_MEDIA_BD" = "1" ]
then
	MEDIA=bluray
	DEST_DIR=video
	(
	generic_mount || exit 1
	prologue && rip_video && generic_umount && epilogue
	) > /tmp/${MEDIA}-rip.${ME} 2>&1 &
elif [ "$ID_CDROM_MEDIA_DVD" = "1" ]
then
	MEDIA=dvd
	DEST_DIR=video
	(
	generic_mount || exit 1
	prologue && rip_video && generic_umount && epilogue
	) > /tmp/${MEDIA}-rip.${ME} 2>&1 &
elif [ "$ID_CDROM_MEDIA_CD" = "1" ]
then
	NO_MOUNT=1
	NO_EJECT=1
	MEDIA=cdrom
	DEST_DIR=music
	(
	generic_mount || exit 1
	prologue && rip_audio && generic_umount && epilogue
	) > /tmp/${MEDIA}-rip.${ME} 2>&1 &
elif [ "$QUEUE_RUN_ONLY" = "1" ]
then
	NO_MOUNT=1
	NO_EJECT=1
	MEDIA=unknown
	DEST_DIR=video
	(
	generic_mount || exit 1
	prologue && rip_video && generic_umount && epilogue
	) > /tmp/${MEDIA}-rip.${ME} 2>&1 &
fi
