#!/bin/bash

ME=$$
PRG=`basename $0`

# Configurable variables/parameters etc.
[ -f /etc/dsc-trg.conf ] && . /etc/dsc-trg.conf

run_encoder() {
	local -a audio_stream=(`audio-info "$1" | audio-prefs ${AUDIO_PREFS_OPTS[@]}`)
	nice -n ${ENCODER_PRIORITY} HandBrakeCLI "${HANDBRAKE_OPTS[@]}" \
		"${audio_stream[@]}" -i "$1" -o "$2"
}

rewrite_filename() {
	rename 's/\.[0-9]+\.mkv$/\.mkv/' "$1"
}

queue_run() {
	local i=1
	local p="${VIDEO_MNT}"
	local name="`echo ${1##*/} | tr A-Z a-z`"

	check_fs "$p" || return 1

	for x in `ls -tr1 */*.q 2> /dev/null`
	do
		e=".${i}.mkv" # Episode
		c="`echo ${x##*/} | sed 's/\.q$//'`" # Category
		d="`echo ${p}/${c}/${name:0:1}/${name}`" # Directory
		f="${TITLE_PREFIX}${name}${TITLE_SUFFIX}" # File name (target)

		x="`ls -tr1 ${x%%/*}/*.mkv`" # Reassign

		# Pre sanity checks...
		mkdir -p "${d}" || return 1
		[ -f "${1}/${x}" ] || return 1
		[ ! -f "${d}/${f}${e}" ] || return 1

		# Encode!
		run_encoder "${1}/${x}" "${d}/${f}${e}" || return 1

		# Post sanity checks...
		[ -s "${d}/${f}${e}" ] || return 1

		# Clean up
		rm -f "${x%%/*}"/*.{q,mkv}
		rmdir "${x%%/*}"
		let i="i + 1"
	done

	[ $i -eq 2 ] && rename "${d}/${f}${e}" || return 0
}

queue_runner() {
	local q="${QUEUE_DIR}"

	while [ `stat -c %h "${q}"` -gt 2 ]
	do
		find "$q" -maxdepth 1 -type d \! -path "$q" | while IFS=$'\n' read d
		do
			cd "$d" || return 1
			queue_run "$d" || return 1
			[ `stat -c %h "$d"` -eq 2 ] && cd - && rmdir "$d"
		done
		sleep 5
	done
}

(
prologue "$PRG" && queue_runner && epilogue "$PRG"
) > ${TMP}/${PRG}.${ME} 2>&1 &
